- name: Create directory for mqtt-tempo
  file:
    state: directory
    path: /opt/mqtt-tempo/bin

- name: Get mqtt-tempo binary
  get_url:
    url: "{{ lookup('vars', 'mqtt_tempo_' + ansible_machine + '_url') }}"
    dest: /opt/mqtt-tempo/bin/mqtt-tempo
    mode: "0755"

- name: create mqtt-tempo service
  template:
     src: mqtt-tempo.service.j2
     dest: /lib/systemd/system/mqtt-tempo.service
     mode: "0644"

- name: install new mqtt-tempo service
  systemd:
    daemon_reload: yes

- name: install new mqtt-tempo service
  systemd:
    enabled: yes
    name: mqtt-tempo
    state: started
